# Generated by Django 3.2.13 on 2022-05-01 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Awaiting payment', 'Awaiting payment'), ('On hold', 'On hold'), ('Processing', 'Processing'), ('Awaiting shipment', 'Awaiting shipment'), ('Is shipped', 'Is shipped'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded')], default='Awaiting payment', max_length=25)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
